# @package _group_
lr: 0.0001
metric: ${metric.metric_name}
mode: "max"
seed: 666
debug: False
n_classes: 10
lightning_module_name: src.lightning_classes.lightning_image_classification.LitImageClassification
data_module_name: src.lightning_classes.datamodule_imagenette.ImagenetteDataModule

#data_module_name: src.lightning_classes.datamodule_mnist.MNISTDataModule
